import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ChessGameGeneratedModule, ChessGameGeneratedSharedModule } from './generated/module.js';
import { ChessGameValidator, registerValidationChecks } from './chess-game-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ChessGameAddedServices = {
    validation: {
        ChessGameValidator: ChessGameValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ChessGameServices = LangiumServices & ChessGameAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ChessGameModule: Module<ChessGameServices, PartialLangiumServices & ChessGameAddedServices> = {
    validation: {
        ChessGameValidator: () => new ChessGameValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createChessGameServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ChessGame: ChessGameServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ChessGameGeneratedSharedModule
    );
    const ChessGame = inject(
        createDefaultModule({ shared }),
        ChessGameGeneratedModule,
        ChessGameModule
    );
    shared.ServiceRegistry.register(ChessGame);
    registerValidationChecks(ChessGame);
    if (!context.connection) {
        // not running inside a language server: initialize the configuration provider at once
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, ChessGame };
}
