import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { VideoGeneratorGeneratedModule, VideoGeneratorGeneratedSharedModule } from './generated/module.js';
import { VideoGeneratorValidator, registerValidationChecks } from './video-generator-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type VideoGeneratorAddedServices = {
    validation: {
        VideoGeneratorValidator: VideoGeneratorValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type VideoGeneratorServices = LangiumServices & VideoGeneratorAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const VideoGeneratorModule: Module<VideoGeneratorServices, PartialLangiumServices & VideoGeneratorAddedServices> = {
    validation: {
        VideoGeneratorValidator: () => new VideoGeneratorValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createVideoGeneratorServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    VideoGenerator: VideoGeneratorServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        VideoGeneratorGeneratedSharedModule
    );
    const VideoGenerator = inject(
        createDefaultModule({ shared }),
        VideoGeneratorGeneratedModule,
        VideoGeneratorModule
    );
    shared.ServiceRegistry.register(VideoGenerator);
    registerValidationChecks(VideoGenerator);
    return { shared, VideoGenerator };
}
